from dataclasses import dataclass
from seedcash.helpers.ur2.cbor_lite import CBOREncoder
from seedcash.helpers.ur2.ur_encoder import UREncoder
from seedcash.helpers.ur2.ur import UR
from seedcash.helpers.qr import QR
from seedcash.models.seed import Seed


@dataclass
class BaseQrEncoder:

    def __post_init__(self):
        self.qr = QR()

    @property
    def is_complete(self):
        raise Exception("Not implemented in child class")

    @property
    def qr_max_fragment_size(self):
        raise Exception("Not implemented in child class")

    def seq_len(self):
        raise Exception("Not implemented in child class")

    def next_part(self) -> str:
        raise Exception("Not implemented in child class")

    def cur_part(self) -> str:
        raise Exception("Not implemented in child class")

    def restart(self):
        # only used by animated QR encoders
        pass

    def _create_parts(self):
        raise Exception("Not implemented in child class")

    def part_to_image(
        self, part, width, height, border: int = 3, background_color: str = "ffffff"
    ):
        return self.qr.qrimage_io(
            part, width, height, border, background_color=background_color
        )

    def next_part_image(
        self, width=240, height=240, border=3, background_color="bdbdbd"
    ):
        part = self.next_part()
        return self.part_to_image(
            part, width, height, border, background_color=background_color
        )


"""**************************************************************************************
    STATIC QR encoders
**************************************************************************************"""


@dataclass
class BaseStaticQrEncoder(BaseQrEncoder):
    def seq_len(self):
        return 1

    def cur_part(self) -> str:
        """static QRs only have a single part, which `next_part` always returns"""
        return self.next_part()

    @property
    def is_complete(self):
        return True


@dataclass
class GenericStaticQrEncoder(BaseStaticQrEncoder):
    data: str = None

    def next_part(self):
        return self.data


@dataclass
class BaseXpubQrEncoder(BaseQrEncoder):
    """
    Base Xpub QrEncoder for static and animated formats
    """

    seed: Seed = None
    derivation: str = None
    sig_type: str = None


"""**************************************************************************************
    Fountain encoded animated QR encoders
**************************************************************************************"""

@dataclass
class BaseFountainQrEncoder(BaseQrEncoder):
    def __post_init__(self):
        super().__post_init__()

        self.ur2_encode: UREncoder = None

    @property
    def is_complete(self):
        return self.ur2_encode.is_complete()

    @property
    def qr_max_fragment_size(self):
        return 65

    def _create_parts(self):
        """parts are dynamically generated by the fountain encoder"""
        pass

    def seq_len(self):
        return self.ur2_encode.fountain_encoder.seq_len()

    def next_part(self) -> str:
        return self.ur2_encode.next_part()

    def cur_part(self) -> str:
        return self.ur2_encode.current_part()

    def restart(self):
        self.ur2_encode.fountain_encoder.restart()


@dataclass
class UrPsbtQrEncoder(BaseFountainQrEncoder):
    psbt: bytearray = None
    qr_max_fragment_size: int = 65

    @staticmethod
    def _wrap_psbt(psbt):
        encoder = CBOREncoder()
        encoder.encodeBytes(psbt)
        return encoder.get_bytes()

    def __post_init__(self):
        super().__post_init__()
        ur = UR("crypto-psbt", self._wrap_psbt(bytes(self.psbt)))
        self.ur2_encode = UREncoder(ur=ur, max_fragment_len=self.qr_max_fragment_size)
